# Generated by Django 3.2 on 2023-04-17 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('healthLabels', models.JSONField()),
                ('ingredientLines', models.JSONField()),
                ('ingredients', models.JSONField()),
                ('calories', models.FloatField()),
                ('nutrients', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedDate', models.CharField(max_length=8, unique=True)),
                ('breakfast', models.ManyToManyField(related_name='breakfast_set', to='mealapp.FoodItem')),
                ('dinner', models.ManyToManyField(related_name='dinner_set', to='mealapp.FoodItem')),
                ('lunch', models.ManyToManyField(related_name='lunch_set', to='mealapp.FoodItem')),
                ('snack', models.ManyToManyField(related_name='snack_set', to='mealapp.FoodItem')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
