# Generated by Django 3.2 on 2023-04-24 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mealapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedDate', models.CharField(max_length=8)),
                ('plannedCalories', models.IntegerField(validators=[mealapp.models.validate_planned_calories])),
                ('breakfast', models.JSONField(default=list)),
                ('lunch', models.JSONField(default=list)),
                ('snack', models.JSONField(default=list)),
                ('dinner', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(fields=('user', 'selectedDate'), name='unique_user_selected_date'),
        ),
    ]
