# Generated by Django 3.2 on 2023-04-17 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='userId',
            new_name='user',
        ),
    ]
