# Generated by Django 3.2 on 2023-04-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0002_rename_userid_meal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='selectedDate',
        ),
        migrations.AddField(
            model_name='meal',
            name='selected_date',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='meal',
            name='breakfast',
        ),
        migrations.AddField(
            model_name='meal',
            name='breakfast',
            field=models.JSONField(default=list),
        ),
        migrations.RemoveField(
            model_name='meal',
            name='dinner',
        ),
        migrations.AddField(
            model_name='meal',
            name='dinner',
            field=models.JSONField(default=list),
        ),
        migrations.RemoveField(
            model_name='meal',
            name='lunch',
        ),
        migrations.AddField(
            model_name='meal',
            name='lunch',
            field=models.JSONField(default=list),
        ),
        migrations.RemoveField(
            model_name='meal',
            name='snack',
        ),
        migrations.AddField(
            model_name='meal',
            name='snack',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
