# Generated by Django 3.2 on 2023-04-18 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0003_auto_20230418_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='selected_date',
            new_name='selectedDate',
        ),
    ]
