# Generated by Django 3.2 on 2023-04-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='allergies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='meal_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
