# Generated by Django 3.2 on 2023-04-29 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_useraccount_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'permissions': [('delete_user', 'Can delete user'), ('update_user', 'Can update user')]},
        ),
    ]
