# Generated by Django 3.2 on 2023-04-29 06:26

from django.db import migrations





class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_useraccount_options'),
    ]

    operations = [
       
    ]
